[profile.default]
solc = '0.8.23'
evm_version = 'paris'                   # Required for L2s (Optimism, Arbitrum, etc.)
match_contract = "_Local"               # Do not run fork tests
sizes = true
verbosity = 3                           # display errors
optimizer_runs = 200
block_number = 14126430
block_timestamp = 1643802347
runs = 4096

[profile.fork] # run via FOUNDRY_PROFILE=fork foundry test
fs_permissions = [{ access = "read", path = "./deployments/mainnet" }] # Get the deployment addresses for forking
match_contract = "_Fork"

[fmt]
number_underscore = "thousands"
multiline_func_header = "all"
wrap_comments = true
