name: Sphinx Dry Run
env:
    SPHINX_API_KEY: ${{ secrets.SPHINX_API_KEY }}
    RPC_ETHEREUM_MAINNET: "https://rpc.ankr.com/eth"
    RPC_ETHEREUM_SEPOLIA: "https://eth-sepolia.g.alchemy.com/v2/${{ secrets.ALCHEMY_API_KEY }}"
    RPC_OPTIMISM_MAINNET: "https://rpc.ankr.com/optimism"
    RPC_OPTIMISM_SEPOLIA: "https://opt-sepolia.g.alchemy.com/v2/${{ secrets.ALCHEMY_API_KEY }}"
    RPC_POLYGON_MAINNET: "https://rpc.ankr.com/polygon"
    RPC_POLYGON_MUMBAI: "https://polygon-mumbai.g.alchemy.com/v2/${{ secrets.ALCHEMY_API_KEY }}"

# Trigger the dry run when a pull request is opened or updated.
on: pull_request

jobs:
  sphinx-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install npm dependencies
        run: npm ci
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
    #   - name: Install Sphinx Solidity Library
    #     run: npx sphinx install
      - name: Dry Run
        run: npx sphinx propose script/Deploy.s.sol --dry-run --networks testnets