name: Slither Analysis
on: [push]
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: onbjerg/foundry-toolchain@v1
      - uses: crytic/slither-action@v0.3.1